name: Build and Release APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Release
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Run Tests
        run: ./gradlew test
      - name: Build Project
        run: ./gradlew assemble
      - name: Build Debug APK
        run: bash ./gradlew :app:assembleDebug
      - name: build release
        run: ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: ${{ github.workspace}} /app/build/outputs/apk/release/app-release.apk