name: Build and Release APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Release
    continue-on-error: true
    steps:
        runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: set up JDK 11
        runs-on: ubuntu-latest
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Add executable permission to gradlew
        run: chmod +x gradlew
      - name: Run Tests
        run: ./gradlew test
      - name: Build Project
        run: ./gradlew assemble
      - name: Build Debug APK
        run: bash ./gradlew :app:assembleDebug
      - name: build release
        run: ./gradlew assembleRelease
      - name: Upload APK
        runs-on: ubuntu-latest
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk